import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

// solution-2 start
import Editor from '../components/Editor'
// --- end

// Solution-1 start
// var Editor = dynamic(() => import("../components/Editor"), {
//   ssr: false
// })
// --- end

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2> CKEditor 5 - Classic Build </h2>
        <Editor />
      </main>
    </div>
  )
}
